### ISSUE TITLE
question about output？

### ISSUE THREAD

**Issue by highway007** [zhuhao-nju/hmd#4]
Thx for your great works.
I wonder if this repo can get joint3d,joint2d and theta like hmr?Or you have plan to do it?

**Comment by zhuhao-nju** [comment]
Thanks, unfortunately our result cannot produce theta, because we refine the mesh in a free-form editing manner, the recovered mesh is not a parametric model anymore.
Joint 3D/2D could be extracted from the recovered mesh by computing the center of "joint handles" for each joint.  "get_joint_posi()" in utility.py does this, and we plan to add evaluation codes in the future.

**Comment by highway007** [comment]
@zhuhao-nju Thanks  for your reply.I will close this issue.
